import { PrismaClient } from '@prisma/client';
const db=new PrismaClient();
const catalog:any[]=[
['DRIP CLIENT (NO ROOT)','APKMOD Freefire','/products/DRIP CLIENT.png',[['1 Hari',12000],['3 Hari',35000],['7 Hari',65000],['15 Hari',85000],['30 Hari',135000]]],['DRIP CLIENT (PROXY)','Proxy Freefire','/products/DRIP CLIENT PROXY.png',[['1 Hari',12000],['3 Hari',30000],['7 Hari',55000],['30 Hari',135000]]],['SILENT CHEATS','APKMOD Freefire','/products/SILENT CHEATS.png',[['1 Hari',15000],['3 Hari',25000],['7 Hari',55000],['14 Hari',90000],['30 Hari',140000]]],['HG CHEAT FF','APKMOD Freefire','/products/HG CHEATS.png',[['1 Hari',15000],['7 Hari',40000],['10 Hari',55000],['30 Hari',115000]]],['HG PROXY','Proxy Freefire','/products/HG PROXY.png',[['1 Hari',13000],['7 Hari',50000],['30 Hari',90000]]],['PRIME HOOK (APK MOD)','APKMOD Freefire','/products/PRIME HOOK.png',[['1 Hari',10000],['3 Hari',25000],['7 Hari',50000]]],['PATO TEAM (ORANGE)','APKMOD Freefire','/products/PATO ORANGE.png',[['3 Hari',45000],['7 Hari',95000],['15 Hari',145000],['30 Hari',250000]]],['PATO TEAM (BLUE)','APKMOD Freefire','/products/PATO BLUE.png',[['3 Hari',35000],['7 Hari',75000],['15 Hari',135000],['30 Hari',195000]]],['BR MODS (ROOT)','APKMOD Freefire',null,[['1 Hari',20000],['7 Hari',35000],['15 Hari',60000],['30 Hari',130000]]]
];
const files:any[]=[['AREA SUNG GACOR','GodData V1 [80%]',20000],['AREA SUNG GACOR','ModData V1 [80%]',20000],['DRAG SHOOT SERIES','Drag Shoot V1 [85%]',20000],['DRAG SHOOT SERIES','Drag Shoot V1 [75%]',18000],['DRAG SHOOT SERIES','Drag Shoot V1 [68%]',14000],['DRAG SHOOT SERIES','Drag Shoot V1 [55%]',8000],['DRAG SHOOT SERIES','Drag Shoot V1 [45%]',5000],['AIM HEADSHOT SERIES','Aim HS V1 [85%]',20000],['AIM HEADSHOT SERIES','Aim HS V1 [72%]',15000],['AIM HEADSHOT SERIES','Aim HS V1 [65%]',10000],['AIM HEADSHOT SERIES','Aim HS V1 [55%]',8000],['AIM HEADSHOT SERIES','Aim HS V1 [50%]',5000],['EASY DRAG SERIES','NYZ Easy Drag [75%]',20000],['EASY DRAG SERIES','NYZ Easy Drag [65%]',15000],['EASY DRAG SERIES','NYZ Easy Drag [52%]',10000],['EASY DRAG SERIES','NYZ Easy Drag [45%]',5000],['AIMLOCK VVIP SERIES','Aimlock VVIP [80%]',20000],['AIMLOCK VVIP SERIES','Aimlock VVIP [75%]',15000],['AIMLOCK VVIP SERIES','Aimlock VVIP [65%]',10000],['AIMLOCK VVIP SERIES','Aimlock VVIP [50%]',5000]];
function slug(s:string){return s.toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'')}
async function main(){
 for(const [name,desc] of [['APKMOD Freefire','Katalog APKMOD Freefire'],['Proxy Freefire','Katalog Proxy Freefire'],['List File Freefire','Katalog List File Freefire']])await db.category.upsert({where:{name},update:{description:String(desc),active:true},create:{name,slug:slug(String(name)),description:String(desc)}});
 for(const [name,categoryName,image,variants] of catalog){const c=await db.category.findUnique({where:{name:categoryName}});const p=await db.product.upsert({where:{slug:slug(name)},update:{name,categoryName,categoryId:c?.id??null,image,active:true},create:{slug:slug(name),name,categoryName,categoryId:c?.id??null,image,active:true,description:'Produk digital NyyyxyzModz. Penggunaan produk memiliki risiko sesuai kebijakan game.'}});for(const [vn,price] of variants)await db.productVariant.upsert({where:{productId_name:{productId:p.id,name:vn}},update:{price,active:true},create:{productId:p.id,name:vn,price,resellerPrice:Math.floor(Number(price)*.9)}})}
 for(const [series,name,price] of files){const categoryName='List File Freefire';const c=await db.category.findUnique({where:{name:categoryName}});const s=slug(name+'-'+series);const p=await db.product.upsert({where:{slug:s},update:{name,categoryName,categoryId:c?.id??null,series,active:true},create:{slug:s,name,categoryName,categoryId:c?.id??null,series,active:true,description:'File digital. Penggunaan merupakan tanggung jawab pengguna.'}});await db.productVariant.upsert({where:{productId_name:{productId:p.id,name:'1 File'}},update:{price,active:true},create:{productId:p.id,name:'1 File',price,resellerPrice:Math.floor(Number(price)*.9)}})}
 const adminEmail=process.env.ADMIN_EMAIL,hash=process.env.ADMIN_PASSWORD_HASH;if(adminEmail&&hash)await db.user.upsert({where:{email:adminEmail},update:{role:'ADMIN',passwordHash:hash,active:true},create:{name:'Nyyyxyz Admin',email:adminEmail,passwordHash:hash,role:'ADMIN',emailVerifiedAt:new Date()}});
 const banners:[string,string,number][]=[['Banner 1','/assets/file_0000000005bc820797fa043a5c9a1bd6.png',0],['Banner 2','/assets/file_000000001600820783c6611febbf3f04.png',1],['Banner 3','/assets/file_00000000f0808211bca0f0d72b1742f2.png',2]];for(const [title,image,sort] of banners)await db.banner.upsert({where:{id:`seed-banner-${sort}`},update:{title,image,sort,active:true},create:{id:`seed-banner-${sort}`,title,image,sort}});
 for(const [key,value] of [['siteName','NyyyxyzModz'],['whatsapp1','6285770528356'],['whatsapp2','62895626791727'],['qris','/assets/qris.png'],['maintenance','false']])await db.siteSetting.upsert({where:{key},update:{value},create:{key,value}});
 console.log('Seed complete')
}main().catch(e=>{console.error(e);process.exit(1)}).finally(()=>db.$disconnect());
