export type Variant={id:string;name:string;price:number;stock:number};
export type Product={id:string;slug:string;name:string;category:string;series:string|null;description:string|null;image:string|null;variants:Variant[]};
const fallbackVariants=(rows:readonly [string,number][],prefix:string):Variant[]=>rows.map(([name,price],i)=>({id:prefix+i,name,price,stock:0}));
export const fallbackProducts:Product[]=[
{name:'DRIP CLIENT (NO ROOT)',category:'APKMOD Freefire',series:null,image:'/products/DRIP CLIENT.png',slug:'drip-client-no-root',id:'f1',description:'Produk digital NyyyxyzModz.',variants:fallbackVariants([['1 Hari',12000],['3 Hari',35000],['7 Hari',65000],['15 Hari',85000],['30 Hari',135000]],'f1v')},
{name:'DRIP CLIENT (PROXY)',category:'Proxy Freefire',series:null,image:'/products/DRIP CLIENT PROXY.png',slug:'drip-client-proxy',id:'f2',description:'Produk digital NyyyxyzModz.',variants:fallbackVariants([['1 Hari',12000],['3 Hari',30000],['7 Hari',55000],['30 Hari',135000]],'f2v')},
{name:'SILENT CHEATS',category:'APKMOD Freefire',series:null,image:'/products/SILENT CHEATS.png',slug:'silent-cheats',id:'f3',description:'Produk digital NyyyxyzModz.',variants:fallbackVariants([['1 Hari',15000],['3 Hari',25000],['7 Hari',55000],['14 Hari',90000],['30 Hari',140000]],'f3v')},
{name:'HG CHEAT FF',category:'APKMOD Freefire',series:null,image:'/products/HG CHEATS.png',slug:'hg-cheat-ff',id:'f4',description:'Produk digital NyyyxyzModz.',variants:fallbackVariants([['1 Hari',15000],['7 Hari',40000],['10 Hari',55000],['30 Hari',115000]],'f4v')},
{name:'HG PROXY',category:'Proxy Freefire',series:null,image:'/products/HG PROXY.png',slug:'hg-proxy',id:'f5',description:'Produk digital NyyyxyzModz.',variants:fallbackVariants([['1 Hari',13000],['7 Hari',50000],['30 Hari',90000]],'f5v')},
{name:'PRIME HOOK (APK MOD)',category:'APKMOD Freefire',series:null,image:'/products/PRIME HOOK.png',slug:'prime-hook-apk-mod',id:'f6',description:'Produk digital NyyyxyzModz.',variants:fallbackVariants([['1 Hari',10000],['3 Hari',25000],['7 Hari',50000]],'f6v')},
{name:'PATO TEAM (ORANGE)',category:'APKMOD Freefire',series:null,image:'/products/PATO ORANGE.png',slug:'pato-team-orange',id:'f7',description:'Produk digital NyyyxyzModz.',variants:fallbackVariants([['3 Hari',45000],['7 Hari',95000],['15 Hari',145000],['30 Hari',250000]],'f7v')},
{name:'PATO TEAM (BLUE)',category:'APKMOD Freefire',series:null,image:'/products/PATO BLUE.png',slug:'pato-team-blue',id:'f8',description:'Produk digital NyyyxyzModz.',variants:fallbackVariants([['3 Hari',35000],['7 Hari',75000],['15 Hari',135000],['30 Hari',195000]],'f8v')},
{name:'BR MODS (ROOT)',category:'APKMOD Freefire',series:null,image:null,slug:'br-mods-root',id:'f9',description:'Fallback visual karena asset resmi produk belum diberikan.',variants:fallbackVariants([['1 Hari',20000],['7 Hari',35000],['15 Hari',60000],['30 Hari',130000]],'f9v')}
];
const fileRows:[string,string,number][]=[['AREA SUNG GACOR','GodData V1 [80%]',20000],['AREA SUNG GACOR','ModData V1 [80%]',20000],['DRAG SHOOT SERIES','Drag Shoot V1 [85%]',20000],['DRAG SHOOT SERIES','Drag Shoot V1 [75%]',18000],['DRAG SHOOT SERIES','Drag Shoot V1 [68%]',14000],['DRAG SHOOT SERIES','Drag Shoot V1 [55%]',8000],['DRAG SHOOT SERIES','Drag Shoot V1 [45%]',5000],['AIM HEADSHOT SERIES','Aim HS V1 [85%]',20000],['AIM HEADSHOT SERIES','Aim HS V1 [72%]',15000],['AIM HEADSHOT SERIES','Aim HS V1 [65%]',10000],['AIM HEADSHOT SERIES','Aim HS V1 [55%]',8000],['AIM HEADSHOT SERIES','Aim HS V1 [50%]',5000],['EASY DRAG SERIES','NYZ Easy Drag [75%]',20000],['EASY DRAG SERIES','NYZ Easy Drag [65%]',15000],['EASY DRAG SERIES','NYZ Easy Drag [52%]',10000],['EASY DRAG SERIES','NYZ Easy Drag [45%]',5000],['AIMLOCK VVIP SERIES','Aimlock VVIP [80%]',20000],['AIMLOCK VVIP SERIES','Aimlock VVIP [75%]',15000],['AIMLOCK VVIP SERIES','Aimlock VVIP [65%]',10000],['AIMLOCK VVIP SERIES','Aimlock VVIP [50%]',5000]];
export const fallbackFiles:Product[]=fileRows.map(([series,name,price],i)=>({id:'file'+i,slug:'file-'+i,name,category:'List File Freefire',series,image:null,description:'File digital. Penggunaan merupakan tanggung jawab pengguna.',variants:[{id:'filev'+i,name:'1 File',price,stock:0}]}));
export const allFallback=[...fallbackProducts,...fallbackFiles];
